/*Ejercicio 1*/
SET SERVEROUTPUT ON;
SET VERIFY OFF;
DECLARE
    CURSOR C (DPTOCOD DEPART.DEPT_NO%TYPE) IS
    SELECT APELLIDO, OFICIO, SALARIO, FECHA_ALT FROM
    EMPLE;
    REG C%ROWTYPE;
    
    CURSOR C2 IS SELECT DEPT_NO, DNOMBRE, LOC FROM DEPART;
    REG2 C2%ROWTYPE;
BEGIN
    OPEN C2;
    LOOP
        FETCH C2 INTO REG2;
        EXIT WHEN C2%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('NUM DEPART ' || REG2.DEPT_NO || ' NOMBRE DEPART: ' || REG2.DNOMBRE || ' LOCALIDAD: ' || REG2.LOC);
        DBMS_OUTPUT.PUT_LINE('APELLIDO        OFICIO      SALARIO    FECHA_ALT');
        DBMS_OUTPUT.PUT_LINE('---------      ---------   ---------   ------------');
        OPEN C (REG2.DEPT_NO);
            LOOP
            FETCH C INTO REG;
            DBMS_OUTPUT.PUT_LINE(RPAD(TO_CHAR(REG.APELLIDO),9,' ' ) || RPAD(TO_CHAR(REG.OFICIO),9,' ' ) || RPAD(TO_CHAR(REG.SALARIO),9,' ' ) ||
            RPAD(TO_CHAR(REG.FECHA_ALT),9,' ' ));
            EXIT WHEN C%NOTFOUND;
        END LOOP;
        CLOSE C;
        DBMS_OUTPUT.PUT_LINE(CHR(10));
    END LOOP;
    CLOSE C2;
END;

/*Ejercicio 2*/
DECLARE
    CURSOR C1 (NUM_COMPRA DET_COMPRAS.NUM_COMPRA%TYPE) IS
    SELECT CODARTI, DENOMINACION, CATEGORIA, PVP,
    (PVP*UNIDADES) IMPORTE, (STOCK-UNIDADES) STOCK_ACTUAL
    FROM ARTICULOS JOIN DET_COMPRAS USING (CODARTI);
    REG1 C1%ROWTYPE;
    
    CURSOR C2 IS SELECT 
    NUM_COMPRA, NOMBRE, FECHA FROM DET_COMPRAS JOIN
    COMPRAS USING (NUM_COMPRA) JOIN ALMACENES USING (CODALMA);
    REG2 C2%ROWTYPE;
BEGIN
    OPEN C2;
    LOOP
        FETCH C2 INTO REG2;
        EXIT WHEN C2%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE('NUM COMRA: ' || REG2.NUM_COMPRA || ' Nombre Almac�n: ' || REG2.NOMBRE);
        DBMS_OUTPUT.PUT_LINE('CODARTI    DENOMINACION   CATEGORIA  UNIDADES   PVP   IMPORTE  STOCK-ACTUAL');
        DBMS_OUTPUT.PUT_LINE('---------  -------------- ---------- ---------- ------ -------- ------------');
        OPEN C1 (REG2.NUM_COMPRA);
        LOOP
            FETCH C1 INTO REG1;
            DBMS_OUTPUT.PUT_LINE(RPAD(TO_CHAR(REG1.CODARTI), 10, ' ') ||
            RPAD(TO_CHAR(REG1.DENOMINACION), 15, ' ') || RPAD(TO_CHAR(REG1.CATEGORIA), 13, ' ')
            || RPAD(TO_CHAR(REG1.PVP)||'�', 6, ' ') || 
            RPAD(TO_CHAR(REG1.IMPORTE)||'�', 9, ' ') || RPAD(TO_CHAR(REG1.STOCK_ACTUAL), 10, ' '));
            EXIT WHEN C1%NOTFOUND;
        END LOOP;
        DBMS_OUTPUT.PUT_LINE(CHR(10));
        CLOSE C1;
    END LOOP;
    CLOSE C2;
END;
