/*1º*/
INSERT INTO ALUMNOS VALUES((SELECT COD_ALUMNO+1 FROM ALUMNOS WHERE COD_ALUMNO = (SELECT MAX(COD_ALUMNO) FROM ALUMNOS)), 'Manuel', 'Engenios', '00112233J','1ºD','C/ Real San Vicente 20 2ºB');

/*2º*/
INSERT INTO PROFESORES VALUES((SELECT COD_PROFESOR+1 FROM PROFESORES WHERE COD_PROFESOR = (SELECT MAX(COD_PROFESOR) FROM PROFESORES)), 'Sanzhez', 'Jose', 'josesan@gmail.com', '1ºA', 1);

/*3º*/
INSERT INTO INCIDENCIAS VALUES((SELECT COD_INCIDENCIA+1 FROM INCIDENCIAS WHERE COD_INCIDENCIA = (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)), 'Tirar Una silla', 3, null);
INSERT INTO INCIDENCIAS VALUES((SELECT COD_INCIDENCIA+1 FROM INCIDENCIAS WHERE COD_INCIDENCIA = (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)), 'Tirar un chicle a la ventana', 5, 'Chicle');
INSERT INTO INCIDENCIAS VALUES((SELECT COD_INCIDENCIA+1 FROM INCIDENCIAS WHERE COD_INCIDENCIA = (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)), 'Jugar con el movil', 10, 'Movil');

/*4º*/
INSERT INTO PARTES VALUES ((SELECT COD_PARTE+1 FROM PARTES WHERE COD_PARTE = (SELECT MAX(COD_PARTE) FROM PARTES)), 21, (SELECT COD_ALUMNO FROM ALUMNOS WHERE DNI_NIE_ALUMNO='00112233J'), 46, 'Inglés', SYSDATE, '3º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=46));
INSERT INTO PARTES VALUES ((SELECT COD_PARTE+1 FROM PARTES WHERE COD_PARTE = (SELECT MAX(COD_PARTE) FROM PARTES)), 21, (SELECT COD_ALUMNO FROM ALUMNOS WHERE DNI_NIE_ALUMNO='00112233J'), 34, 'Lengua', SYSDATE+2, '1º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=34));
INSERT INTO PARTES VALUES ((SELECT COD_PARTE+1 FROM PARTES WHERE COD_PARTE = (SELECT MAX(COD_PARTE) FROM PARTES)), 21, (SELECT COD_ALUMNO FROM ALUMNOS WHERE DNI_NIE_ALUMNO='00112233J'), 30, 'Inglés', SYSDATE+12, '6º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=30));

/*5º*/
INSERT INTO EXPULSIONES VALUES ((SELECT COD_EXPULSION+1 FROM EXPULSIONES WHERE COD_EXPULSION = (SELECT MAX(COD_EXPULSION) FROM EXPULSIONES)), SYSDATE, SYSDATE+20);

/*6º*/
INSERT INTO PARTES_EXPULSION VALUES ((SELECT COD_PARTE_EXPULSION+1 FROM PARTES_EXPULSION WHERE COD_PARTE_EXPULSION = (SELECT MAX(COD_PARTE_EXPULSION) FROM PARTES_EXPULSION)),
21, 21, (SELECT COD_ALUMNO FROM ALUMNOS WHERE DNI_NIE_ALUMNO='00112233J'), 46, 'Inglés', SYSDATE, '3º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=46));
INSERT INTO PARTES_EXPULSION VALUES ((SELECT COD_PARTE_EXPULSION+1 FROM PARTES_EXPULSION WHERE COD_PARTE_EXPULSION = (SELECT MAX(COD_PARTE_EXPULSION) FROM PARTES_EXPULSION)),
21, 21, (SELECT COD_ALUMNO FROM ALUMNOS WHERE DNI_NIE_ALUMNO='00112233J'), 34, 'Lengua', SYSDATE+2, '1º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=34));
INSERT INTO PARTES_EXPULSION VALUES ((SELECT COD_PARTE_EXPULSION+1 FROM PARTES_EXPULSION WHERE COD_PARTE_EXPULSION = (SELECT MAX(COD_PARTE_EXPULSION) FROM PARTES_EXPULSION)),
21, 21, (SELECT COD_ALUMNO FROM ALUMNOS WHERE DNI_NIE_ALUMNO='00112233J'), 30, 'Inglés', SYSDATE+12, '6º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=30));

/*7º*/
DELETE FROM PARTES_EXPULSION WHERE COD_EXPULSION=21;

/*8º*/
INSERT INTO INCIDENCIAS VALUES ((SELECT COD_INCIDENCIA+1 FROM INCIDENCIAS WHERE COD_INCIDENCIA = (SELECT MAX(COD_INCIDENCIA) FROM INCIDENCIAS)), 'Abrir una Coca Cola en clase', 10, 'Abrir');

/*9º*/
UPDATE PARTES SET PUNTOS_PARTE = DECODE(PUNTOS_PARTE, 3, PUNTOS_PARTE-1, 5, PUNTOS_PARTE-2, PUNTOS_PARTE);

/*10º*/
UPDATE INCIDENCIAS SET DESCRIPCION_INCIDENCIA = 'Insultar' WHERE NOM_INCIDENCIA='Insultar a un compañero.';

/*11º*/
INSERT INTO ALUMNOS VALUES((SELECT COD_ALUMNO+1 FROM ALUMNOS WHERE COD_ALUMNO = (SELECT MAX(COD_ALUMNO) FROM ALUMNOS)), 'Raúl', (SELECT APE_ALUMNO FROM ALUMNOS WHERE COD_ALUMNO=11),
'648773', (SELECT GRUPO_ALUMNO FROM ALUMNOS WHERE COD_ALUMNO=11), (SELECT DIR_ALUMNO FROM ALUMNOS WHERE COD_ALUMNO=11));

/*12º*/
INSERT INTO EXPULSIONES SELECT (MAX(COD_EXPULSION)+1), SYSDATE, (SYSDATE+4) FROM EXPULSIONES;

/*13º*/
INSERT INTO PARTES VALUES((SELECT COD_PARTE+1 FROM PARTES WHERE COD_PARTE = (SELECT MAX(COD_PARTE) FROM PARTES)), 11, 10, (SELECT COD_INCIDENCIA FROM INCIDENCIAS WHERE NOM_INCIDENCIA='Agresión.')
, 'Informática', SYSDATE, '2º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=34));

/*14º*/
INSERT INTO PARTES VALUES((SELECT COD_PARTE+1 FROM PARTES WHERE COD_PARTE = (SELECT MAX(COD_PARTE) FROM PARTES)), (SELECT COD_PROFESOR FROM PROFESORES WHERE NOM_PROFESOR='Pedro' AND 
APE_PROFESOR='Madrid'), (SELECT COD_ALUMNO FROM ALUMNOS WHERE NOM_ALUMNO='Luis' AND APE_ALUMNO='Martín Jiménez'), (SELECT COD_INCIDENCIA FROM INCIDENCIAS WHERE NOM_INCIDENCIA='Robo.'),
'Matemáticas', SYSDATE, '5º hora', (SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE COD_INCIDENCIA=35));

/*15º*/
UPDATE PARTES SET COD_PROFESOR=(SELECT COD_PROFESOR FROM PROFESORES WHERE EMAIL_PROFESOR='adrian@gmail.com') WHERE COD_PARTE=7;

/*16º*/
UPDATE ALUMNOS SET GRUPO_ALUMNO = '2ºB' WHERE DNI_NIE_ALUMNO='758755';

/*17º*/
UPDATE ALUMNOS SET GRUPO_ALUMNO='2ºA' WHERE COD_ALUMNO NOT IN (SELECT COD_ALUMNO FROM PARTES);

/*18º*/
DELETE PARTES WHERE PUNTOS_PARTE<(SELECT PUNTOS_INCIDENCIA FROM INCIDENCIAS WHERE NOM_INCIDENCIA='Llegar tarde a clase.');

/*19º*/
DELETE PARTES WHERE COD_PROFESOR IN (SELECT COD_PROFESOR FROM PROFESORES WHERE TIPO_PROFESOR=2);

/*20º*/
DELETE PARTES WHERE PUNTOS_PARTE < 5 AND TRUNC(months_between(FECHA_PARTE, SYSDATE)) = 6;
